#!/usr/local/bin/perl -pi.bak -0777

s/^(my \$attr_spec.+?^])/insert_help($1)/egsm ;

sub insert_help {

	my( $text ) = @_ ;

	$text =~ s[^\s+},][<<SUB]eg ;
		'help'		=> <<HELP,
HELP
	},
SUB

	$text =~ s/=>\t/=> /g ;

	return $text ;
}
