#!/usr/local/bin/perl -n

next if /^\s*$/ ;

next if /^\s*#/ ;

next if /^=head/ .. /^=cut/ ;

next if ($line = /::Test/ ... /^package/) and $line !~ /E/ ;
#next if /::Test/ ... /^package/ ;

$lines++ ;

END { print "$lines\n" }
